### ISSUE TITLE
Flyer Meeting Agenda 2016MAR16

### ISSUE THREAD

**Issue by mjcarroll** [coworkal/coworkal.github.io#6]
Let's talk about things:
- Different views that are more appropriate for digital signage.
- Domain/Subdomain/Nameserver handling
- Nav buttons on the flyer/schedule for forwards/backwards/up

**Comment by drewmcdowell** [comment]
Let's discuss how we can develop coworkal.com as a tool for:
- Marketing Coworking Night and specific events to potential attendees
  ideas: create front page "What is Coworking Night", show visitors FB friends who belong to CN group, generate cards/flyers to leave around town or hand out?, remove requirement to log into Facebook to view page
- Onboarding new attendees
  ideas: generate map/schedule for tv screen, generate new-attendee-oriented printed flyers, direct attendees to mobile website with "First-timer?" page,
- Informing current attendees of schedules and locations
  ideas: generate map/schedule for tv screen, generate printed flyers, direct attendees to mobile website with schedule/map perhaps with auto-updating "Happening Now" and "Coming Up" listings
- Helping organizers...organize. More effectively/efficiently
  ideas: user-friendly sign-in sheet, user-friendly attendance analytics, encouraging attendees to RSVP, automate room assignment by requirement (time, size, equipment)
